name: Bug Report
description: Report something not behaving as expected
labels: ["bug"]
assignees:
  - franky47
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Not required, but strongly recommended for behavioural issues.
      placeholder: URL to a CodeSandbox or a GitHub repo
  - type: input
    id: nuqs-version
    attributes:
      label: What version of next-usequerystate are you using?
      description: Run `cat package.json | grep next-usequerystate` to find out.
      placeholder: ex. 1.9.2
    validations:
      required: true
  - type: textarea
    id: next-version
    attributes:
      label: What version of Next.js are you using?
      description: Run `next info` and paste the result here.
      placeholder: Output from `next info`
    validations:
      required: true
  - type: dropdown
    id: routers
    attributes:
      label: Where does the problem occur?
      multiple: true
      options:
        - App router
        - Pages router
  - type: dropdown
    id: browsers
    attributes:
      label: What **browsers** are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: platforms
    attributes:
      label: What **platforms** are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
        - Android
        - iOS
  - type: textarea
    id: logs
    attributes:
      label: Relevant debug log output
      description: Enable [debugging](https://github.com/47ng/next-usequerystate#debugging), then please copy and paste any relevant log output. No need for backticks.
      render: Text

